### PR TITLE
Updated SDL include path

### PR DESCRIPTION
**Pull request by Shambler2**
Feel free to delete but thought I'd put this up here just in case - not sure if this would be breaking anything in the mainline PCEM?

### CODE REVIEW

**Comment by kyr0** [comment]
Thank you @Shambler2 :) -- if this is Apple-specific, we might want to make it conditional to the Mac platform using preprocessor statements instead of changing the code. Only the code that matches these conditions will then be visible to the actual compiler frontend on the system where you run the compilation. You can also have deep branching like if, if, endif, endif, etc. An example: https://github.com/PCemOnMac/PCemV17macOS/blob/eb0bf7379e0a9e82804e9ee91368dde2a126c96c/src/pc.c#L4

Regarding include-paths like this, we might also want to check if these are platform-specific and maybe also OS version-specific.

**Comment by Shambler2** [comment]
Thanks! I did notice many of the fixes used in the recent merge included these statements so I'd imagine that would be the best approach. If it is as you suggested that it is an ARM specific issue it'd be good to validate that - though I've only got the one machine at the moment to test with

**Comment by kyr0** [comment]
Yep, maybe let's wait for @kode54 opinion on this. I can at least check with my Catalina Intel machine.

**Comment by kode54** [comment]
Seems to build fine.

**Pull request merged**
